#!/bin/bash
#Shutdown any existing Steam processes first
steam -shutdown
sleep 5
pkill steam
sleep 5

# Launch a Gamescope session with SteamDeck like options.
gamescope \
    -e \
    -f \
    -o 144 \
    -r 144 \
    --backend auto \
    -C 3000 \
    --max-scale 2 \
    --xwayland-count 2 \
    -w 1920 -h 1080 \
    -W 1920 -H 1080 \
    --generate-drm-mode fixed \
    --framerate-limit 144 \
    --adaptive-sync \
    --mangoapp \
    --fade-out-duration 200 \
    -- steam -steamdeck -steamos3 \
    &
gamescope_pid=$!

# Monitor for Steam processes and relaunch if it's not running ie. Switching to Desktop Mode
monitor_steam() {
  while kill -0 "$gamescope_pid" &> /dev/null; do
    sleep 5
    if ! pgrep -u "$USER" -x "steam" > /dev/null; then
      echo "Steam process not found. Relaunching..."
      steam &
      sleep 5
    fi
  done
  echo "Gamescope session ended."
}

# Run the monitoring function in the background
monitor_steam &

# Keep the script running until Gamescope exits
wait "$gamescope_pid"

