#!/bin/sh

sleep 20
#Update existing OS first
pacman -Syu --noconfirm
yay -Syu --noconfirm
#Removal of any unwanted packages
pacman -Rdd --noconfirm blueman
pacman -Rdd --noconfirm kmix
pacman -Rdd --noconfirm gnome-terminal
pacman -Rdd --noconfirm gedit
pacman -Rdd --noconfirm plasma-wayland-session
#Remove any unwanted files
rm /usr/local/bin/coffeebrewer-cinnamon
#rm /usr/local/bin/coffeebrewer-kde
rm /usr/local/bin/coffeebrewer-sway
rm -R /usr/share/wayland-sessions/gnome*
rm -R /usr/share/xsessions/gnome*
rm /usr/share/applications/steam-native.desktop
rm /usr/share/applications/stoken-gui-small.desktop
exit
