#!/bin/sh

sleep 10
#Update the system first
pacman -Syu --noconfirm
#Latest Coffee Linux Raw Updates
pacman -Sy --noconfirm wget
rm /opt/yay-12.2.0-1-x86_64.pkg.tar.zst
rm /opt/yay-12.3.1-3-x86_64.pkg.tar.zst
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/yay-12.3.1-3-x86_64.pkg.tar.zst -P /opt/
pacman -U --noconfirm /opt/yay-12.3.1-3-x86_64.pkg.tar.zst
#27.7.4 Patch
rm /opt/pacman-stable.conf
rm /opt/pacman-unstable.conf
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/pacman-stable.conf -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/pacman-unstable.conf -P /opt/
cp /opt/pacman-stable.conf /etc/pacman.conf
pacman -Rdd pamac-aur
#27.7.9 Patch
rm /etc/issue
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/issue -P /opt/
cp /opt/issue /etc/
#Replace CoffeeLinux Files
rm /opt/os-release
rm /opt/lsb-release
rm /etc/os-release
rm /etc/lsb-release
rm /opt/coffee-injector
rm /opt/config
rm /usr/local/bin/coffeebrewer-custom
rm /usr/local/bin/coffeebrewer-gnome
rm /usr/local/bin/coffeebrewer-kde
rm /usr/local/bin/coffeebrewer-mainmenu
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/config -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/coffee-injector -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/os-release -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/lsb-release -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/os-release -P /etc/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/lsb-release -P /etc/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/usr/local/bin/coffeebrewer-custom -P /usr/local/bin/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/usr/local/bin/coffeebrewer-gnome -P /usr/local/bin/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/usr/local/bin/coffeebrewer-kde -P /usr/local/bin/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/usr/local/bin/coffeebrewer-mainmenu -P /usr/local/bin/
chmod 755 /opt/coffee-injector
chmod 755 /usr/local/bin/coffeebrewer-custom
chmod 755 /usr/local/bin/coffeebrewer-gnome
chmod 755 /usr/local/bin/coffeebrewer-kde
chmod 755 /usr/local/bin/coffeebrewer-mainmenu
#Removal of any unwanted packages
pacman -Rdd --noconfirm blueman
pacman -Rdd --noconfirm kmix
pacman -Rdd --noconfirm gnome-terminal
pacman -Rdd --noconfirm gedit
pacman -Rdd --noconfirm plasma-wayland-session
#Disable unwanted services
systemctl disable --now coffee-wallpapers.service
systemctl disable --now coffee-updater.service
#Remove any unwanted files
rm /opt/coffee-updater
rm /opt/wallpaper-updater
rm /opt/coffee-wallpapers.service
rm /opt/coffee-updater.service
rm /lib/systemd/system/coffee-wallpapers.service
rm /lib/systemd/system/coffee-updater.service
rm -R /usr/share/wayland-sessions/gnome*
rm -R /usr/share/xsessions/gnome*
rm /usr/share/applications/steam-native.desktop
rm /usr/share/applications/stoken-gui-small.desktop
#Fix the wallpapers if needed
mkdir -p /usr/share/wallpapers/coffee/
mkdir -p /usr/share/backgrounds/gnome/
cp /opt/backgrounds/coffee/* /usr/share/backgrounds/gnome/
cp /opt/backgrounds/coffee/* /usr/share/wallpapers/coffee/
exit
