#!/bin/sh

rm -R /usr/share/wayland-sessions/gnome*
rm -R /usr/share/xsessions/gnome*
pacman -Rdd --noconfirm gnome-terminal
pacman -Rdd --noconfirm gedit
pacman -Syy --noconfirm gnome-console
pacman -Syy --noconfirm gnome-text-editor
exit
