#!/bin/sh

#Main Menu
while [ "$typecheck00" != "4" ]; do
clear
printf "%b" "\n#### Coffee Linux Updater Tool 1.0.6 ####\n"
printf "%b" "\n#### DO NOT RUN AS SUDO/ROOT ####\n"
printf "%b" "\nWhat type of updates do you want? (Default: 1)\n"
printf "%b" "\n1 - Arch Linux Official\n"
printf "%b" "\n2 - AUR updates\n"
printf "%b" "\n3 - Coffee Linux OS update\n"
printf "%b" "\n4 - Exit the program.\n"

read -r typecheck00
case $typecheck00 in
 1) printf "%b" "\nOfficial updates selected. Running now..\n" ;;
 2) printf "%b" "\nAUR updates selected. Running now...\n" ;;
 3) printf "%b" "\nCoffeeLinux OS update selected. Running now...\n" ;;
 4) printf "%b" "\nExit selected. exiting now...\n" ;;
 *) printf "%b" "\nUnrecognized option, selecting default..\n" ;;
esac

clear

if [ "$typecheck00" = "1" ]; then
sudo pacman -Syu
clear
printf "%b" "\nOfficial Arch Linux updates finished..\n\n"
fi
if [ "$typecheck00" = "2" ]; then
yay -Syu
clear
printf "%b" "\nAUR updates finished...\n\n"
fi
if [ "$typecheck00" = "3" ]; then
sudo bash /opt/coffee-injector
clear
printf "%b" "\nCoffeeLinux OS update finished...\n\n"
fi
if [ "$typecheck00" = "4" ]; then
clear
printf "%b" "\nExited program successfully...\n\n"
fi
if [ "$typecheck00" != "1" ] && [ "$typecheck00" != "2" ] && [ "$typecheck00" != "3" ] && [ "$typecheck00" != "4" ]; then
typecheck00=1
sudo pacman -Syu
clear
printf "%b" "\nOfficial Arch Linux updates finished...\n\n"
fi
done
