#!/bin/sh

rm /opt/coffee-keeper
sleep 30
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/coffee-keeper -P /opt/
chmod 755 /opt/coffee-keeper

exit
