#!/bin/sh

pacman -Syu --noconfirm
yay -Syu --noconfirm --aur
rm /opt/os-release
rm /opt/lsb-release
rm /etc/os-release
rm /etc/lsb-release
rm /usr/local/bin/coffeebrewer-custom
rm /usr/local/bin/coffeebrewer-cinnamon
rm /usr/local/bin/coffeebrewer-kde
rm /usr/local/bin/coffeebrewer-gnome
rm /usr/local/bin/coffeebrewer-sway
wget -L https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso%20mod/releng/airootfs/opt/os-release -P /opt/
wget -L https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso%20mod/releng/airootfs/opt/lsb-release -P /opt/
wget -L https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso%20mod/releng/airootfs/opt/coffeebrewer-custom -P /opt/
wget -L https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso%20mod/releng/airootfs/opt/coffeebrewer-kde -P /opt/
wget -L https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso%20mod/releng/airootfs/opt/coffeebrewer-cinnamon -P /opt/
wget -L https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso%20mod/releng/airootfs/opt/coffeebrewer-gnome -P /opt/
wget -L https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso%20mod/releng/airootfs/opt/coffeebrewer-sway -P /opt/
cp /opt/coffeebrewer-custom /usr/local/bin/
cp /opt/coffeebrewer-kde /usr/local/bin/
cp /opt/coffeebrewer-gnome /usr/local/bin/
cp /opt/coffeebrewer-cinnamon /usr/local/bin/
cp /opt/coffeebrewer-sway /usr/local/bin/
cp /opt/os-release /etc/
cp /opt/lsb-release /etc/
rm -R /opt/coffeebrewer*
chmod 755 /usr/local/bin/coffeebrewer-custom
chmod 755 /usr/local/bin/coffeebrewer-kde
chmod 755 /usr/local/bin/coffeebrewer-gnome
chmod 755 /usr/local/bin/coffeebrewer-cinnamon
chmod 755 /usr/local/bin/coffeebrewer-sway
rm -R /usr/share/wayland-sessions/gnome*
rm -R /usr/share/xsessions/gnome*
#Coffee Package Updates
pacman -Sy --noconfirm wget xdotool yad tinyxxd python-pyqt6 python-pyqt5 python-opengl qt5-serialport qt5-connectivity qt5-remoteobjects qt5-quick3d at-spi2-core packagekit packagekit-qt5 packagekit-qt6 libpackagekit-glib dbus-broker-units
exit
