#!/bin/sh

sleep 10
#Latest Coffee Package Updates
newcontent="python-pipx"
pacman -Sy --noconfirm $newcontent
#Disable unwanted services
systemctl disable --now coffee-wallpapers.service
systemctl disable --now coffee-updater.service
#Remove any unwanted files
rm /opt/coffee-wallpapers.service
rm /opt/coffee-updater.service
rm /lib/systemd/system/coffee-wallpapers.service
rm /lib/systemd/system/coffee-updater.service
#Replace CoffeeLinux Files
rm /opt/os-release
rm /opt/lsb-release
rm /etc/os-release
rm /etc/lsb-release
rm /opt/coffee-injector
rm /opt/coffee-updater
rm /opt/wallpaper-updater
rm /opt/config
rm /usr/local/bin/coffeebrewer-custom
rm /usr/local/bin/coffeebrewer-gnome
rm /usr/local/bin/coffeebrewer-mainmenu
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/config -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/coffee-injector -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/wallpaper-updater -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/coffee-updater -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/os-release -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/lsb-release -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/os-release -P /etc/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/opt/lsb-release -P /etc/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/usr/local/bin/coffeebrewer-custom -P /usr/local/bin/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/usr/local/bin/coffeebrewer-gnome -P /usr/local/bin/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso%20mod/releng/airootfs/usr/local/bin/coffeebrewer-mainmenu -P /usr/local/bin/
chmod 755 /opt/wallpaper-updater
chmod 755 /opt/coffee-updater
chmod 755 /opt/coffee-injector
chmod 755 /usr/local/bin/coffeebrewer-custom
chmod 755 /usr/local/bin/coffeebrewer-gnome
chmod 755 /usr/local/bin/coffeebrewer-mainmenu
exit
