#!/bin/sh

#Main Menu
while [ "$typecheck00" != "1" ] && [ "$typecheck00" != "2" ]; do
clear
printf "%b" "\n#### Coffee Linux Pacman Switcher Tool ####\n"
printf "%b" "\nWhat type of pacman repo do you want? (Default: 1)\n"
printf "%b" "\n1 - Stable\n"
printf "%b" "\n2 - Testing\n"

read -r typecheck00
case $typecheck00 in
 1) printf "%b" "\nPerfect\n" ;;
 2) printf "%b" "\nLet's move on then.\n" ;;
 *) printf "%b" "\nUnrecognized option, selecting default..\n" ;;
esac

if [ "$typecheck00" = "1" ]; then
rm /etc/pacman.conf
cp /opt/pacman-stable.conf /etc/pacman.conf
fi
if [ "$typecheck00" = "2" ]; then
rm /etc/pacman.conf
cp /opt/pacman-unstable.conf /etc/pacman.conf
fi
if [ "$typecheck00" != "1" ] && [ "$typecheck00" != "2" ]; then
typecheck00=1
rm /etc/pacman.conf
cp /opt/pacman-stable.conf /etc/pacman.conf
fi
done
