#!/bin/sh

mkdir -p /usr/share/wallpapers/coffee/
mkdir -p /usr/share/backgrounds/gnome/
cp /opt/backgrounds/coffee/* /usr/share/backgrounds/gnome/
cp /opt/backgrounds/coffee/* /usr/share/wallpapers/coffee/
exit
