#!/bin/sh

mkdir -p /usr/share/wallpapers/coffee/
mkdir -p /usr/share/backgrounds/gnome/
cp /opt/backgrounds/coffee/* /usr/share/backgrounds/gnome/
cp /opt/backgrounds/coffee/* /usr/share/wallpapers/coffee/
rm -R /usr/share/wayland-sessions/gnome*
rm -R /usr/share/xsessions/gnome*
exit
