#!/bin/sh

#Replace service file first.
rm /opt/coffee-keeper.service
rm /lib/systemd/system/coffee-keeper.service
rm /opt/coffee-keeper
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso/releng/airootfs/opt/coffee-keeper.service -P /opt/
wget -L https://raw.githubusercontent.com/Project-X-Mods/coffeelinux/master/coffeelinux-archiso/releng/airootfs/opt/coffee-keeper -P /opt/
cp /opt/coffee-keeper.service /lib/systemd/system/
chmod 755 /opt/coffee-keeper
chmod 755 /lib/systemd/system/coffee-keeper.service
systemctl enable coffee-keeper.service

#Run updater script now
bash /opt/coffee-keeper

exit
