#!/bin/sh

#Replace service file first.
rm /lib/systemd/system/coffee-keeper.service
rm /opt/coffee-keeper
wget -q -O /opt/coffee-keeper.service https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/coffee-keeper.service
wget -q -O /opt/coffee-keeper https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/coffee-keeper
cp /opt/coffee-keeper.service /lib/systemd/system/
chmod 755 /opt/coffee-keeper
chmod 755 /lib/systemd/system/coffee-keeper.service
systemctl enable coffee-keeper.service

#Run updater script now
bash /opt/coffee-keeper

exit
