#!/bin/sh
#Coffee Auto-Updater tool
sleep 3
#All systems go..
system_updates () {
#Do system updates to all packages
clear
printf "%b" "\nUpdating Arch Linux OS files..\n"
sleep 3
clear
pacman -Syu --noconfirm
pacman -Syy --noconfirm btop
pacman -Syy --noconfirm ghostty
clear
#Add temp user for yay updates
user01="temp"
userpass0="password"
printf "%b" "\nPreparing AUR environment..\n"
sleep 3
clear
useradd -m -G wheel,audio,video,users,storage,power,rfkill,lp $user01
printf "%b" "$userpass0\n$userpass0\n" | passwd $user01
clear
printf "%b" "\nPreparing to use temporary AUR environment..\n"
sleep 3
#Run yay commands
clear
printf "%b" "\nUpdating current AUR applications..\n"
sleep 3
clear
sudo -Su "$user01" yay -Syu
clear
printf "%b" "\nAdding any new AUR applications..\n"
sleep 3
clear
printf "%b" "1\n" | sudo -Su "$user01" yay --noconfirm --diffmenu=false --noremovemake --answerclean a --answerdiff n --answeredit y --answerupgrade y shelly
clear
#Remove temporary user
printf "%b" "\nCleaning up afterwards..\n"
sleep 3
userdel -r $user01
sudo pkill -u $user01
sudo Preparing yay environmentuserdel -rf $user01
clear
#Remove any unwanted files if they exist.
pacman -Rdd konsole
pacman -Rdd pamac-aur
clear
}

steamos_mode_updates () {
#Replace SteamOS Mode specific files
clear
printf "%b" "\nReplacing SteamOS Mode files..\n"
sleep 3
clear
steamosmodetype00=$(basename -a /usr/bin/steamos-upd*)
if [ "$steamosmodetype00" = "steamos-update" ]; then
wget -q -O /usr/bin/steamos-update https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/steamos/steamos-update
wget -q -O /usr/bin/steamos-select-branch https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/steamos/steamos-select-branch
wget -q -O /usr/bin/steamos-session-select https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/steamos/steamos-session-select
wget -q -O /usr/bin/jupiter-biosupdate https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/steamos/jupiter-biosupdate
wget -q -O /usr/share/applications/SteamOS.desktop https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/steamos/SteamOS.desktop
chmod +x /usr/bin/steamos-select-branch /usr/bin/steamos-update /usr/bin/steamos-session-select /usr/bin/jupiter-biosupdate
chmod 644 /usr/share/applications/SteamOS.desktop
fi
steamosmodetype01=$(basename -a /usr/bin/gamescope-session*)
if [ "$steamosmodetype01" != "gamescope-session" ]; then
wget -q -O /usr/bin/gamescope-session https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/steamos/gamescope-session
chmod +x /usr/bin/gamescope-session
fi
clear
}

coffeelinux_updates () {
#Replace CoffeeLinux specific files
clear
printf "%b" "\nUpdating CoffeeLinux OS files..\n"
sleep 3
clear
wget -q -O /usr/local/bin/coffee-filter https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/usr/local/bin/coffee-filter
wget -q -O /usr/share/applications/coffee-filter.desktop https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/usr/share/applications/coffee-filter.desktop
wget -q -O /opt/pacman-stable.conf https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/pacman-stable.conf
wget -q -O /opt/pacman-unstable.conf https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/pacman-unstable.conf
wget -q -O /etc/issue https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/issue
cp /opt/issue /etc/
wget -q -O /opt/coffee-updater https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/coffee-updater
cp /opt/coffee-updater /usr/local/bin/
wget -q -O /opt/coffee-updater.desktop https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/coffee-updater.desktop
cp /opt/coffee-updater.desktop /usr/share/applications/
wget -q -O /opt/os-release https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/os-release
wget -q -O /opt/lsb-release https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/lsb-release
wget -q -O /etc/os-release https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/os-release
wget -q -O /etc/lsb-release https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/lsb-release
wget -q -O /usr/local/bin/coffee-brewer https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/usr/local/bin/coffee-brewer
wget -q -O /usr/local/bin/coffee-barista https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/usr/local/bin/coffee-barista
#Set permissions
chmod +x /usr/local/bin/coffee-barista /usr/local/bin/coffee-filter /opt/coffee-updater /opt/coffee-keeper /opt/coffee-injector
chmod 644 /usr/share/applications/coffee-updater.desktop /usr/share/applications/coffee-filter.desktop
chmod 755 /lib/systemd/system/coffee-keeper.service
chmod 644 /etc/issue
systemctl enable coffee-keeper.service
clear
}

gaming_fixes_updater () {
# OS Fixes..
clear
printf "%b" "\nSetting gaming fixes..\n"
sleep 3
clear
#Enable NTSync...
printf "%b" "\nntsync" > /etc/modules-load.d/ntsync.conf
#DotNet 4.8 ie: Space Engineers..
printf "%b" "abi <abi/4.0>,\ninclude <tunables/global>\n\nprofile bwrap /usr/bin/bwrap flags=(unconfined) {\n  userns,\n\n\n  # Site-specific additions and overrides. See local/README for details.\n  include if exists <local/bwrap>\n}\n" > /etc/apparmor.d/bwrap
printf "%b" "abi <abi/4.0>,\ninclude <tunables/global>\n\nprofile srt-bwrap /home/*/.local/share/Steam/**/srt-bwrap flags=(unconfined) {\n  userns,\n  capability setpcap,\n  /proc/*/uid_map rw,\n  /proc/*/gid_map rw,\n  /proc/*/setgroups rw,\n\n  # Prevent transition to the restrictive unprivileged_userns profile\n  change_profile -> unconfined,\n\n  # Site-specific additions and overrides\n  include if exists <local/srt-bwrap>\n}\n" > /etc/apparmor.d/srt-bwrap
apparmor_parser -r /etc/apparmor.d/bwrap
apparmor_parser -r /etc/apparmor.d/srt-bwrap
systemctl restart apparmor
systemctl disable dhcpcd
# VM Max Map Count Fix ie: Horizon Zero Dawn..
printf "%b" "vm.max_map_count=262144" > /etc/sysctl.d/99-vm.max_map_count.conf
clear
}

updater_file_replacer () {
#Injector-Replacer
clear
printf "%b" "\nReplacing updater files..\n"
sleep 3
clear
wget -q -O /opt/coffee-injector https://raw.githubusercontent.com/LiquidSmokeX64/coffee/master/coffeelinux-archiso/releng/airootfs/opt/coffee-injector
chmod 755 /opt/coffee-injector
clear
}

operations_runner () {
clear
printf "%b" "\nStarting System Update procedures..\n"
sleep 3
clear
system_updates
steamos_mode_updates
coffeelinux_updates
gaming_fixes_updater
updater_file_replacer
clear
}

operations_runner
clear
sleep 3
exit
