#!/bin/sh

#Main Menu
while [ "$typecheck00" != "1" ] && [ "$typecheck00" != "2" ]; do
clear
printf "%b" "\n#### Coffee Linux Iso Maker Tool 1.0.9 ####\n"
printf "%b" "\n#### DO NOT RUN AS SUDO/ROOT ####\n"
printf "%b" "\nWhat would you like to do? (Default: 1)\n"
printf "%b" "\n1 - Create a CoffeeLinux iso\n"
printf "%b" "\n2 - Exit the program\n"

read -r typecheck00
case $typecheck00 in
 1) printf "%b" "\nCreate Iso selected. Running now..\n" ;;
 2) printf "%b" "\nExit selected.. Exiting now\n" ;;
 *) printf "%b" "\nUnrecognized option, selecting default..\n" ;;
esac

clear

if [ "$typecheck00" = "1" ]; then
sudo pacman -Syy --noconfirm archiso
sudo rm -R ~/coffeelinux/
sudo rm -R ~/work/ ~/out/
git clone https://github.com/Project-X-Mods/coffeelinux.git
mkdir -p ~/coffeelinux/releng/
cp -R /usr/share/archiso/configs/releng/* ~/coffeelinux/releng/
cp -R ~/coffeelinux/coffeelinux-archiso/releng/* ~/coffeelinux/releng/
sudo mkarchiso -v -w ~/work/ -o ~/out/ ~/coffeelinux/releng/
cp ~/out/coffee* ~/Documents/
sudo rm -R ~/work/ ~/out/
sudo rm -R ~/coffeelinux/
clear
printf "%b" "\nCreated Iso file successfully...\n"
printf "%b" "\nIso will be placed in Documents folder.\n"
printf "%b" "\n#######Press enter to continue.#######.\n"
read -r endcheck00
if [ "$endcheck00" != "g7y26rx105f6gh87stxy4" ]; then
printf "%b" "\nExiting the program now...\n\n"
fi
if [ "$endcheck00" = "g7y26rx105f6gh87stxy4" ]; then
printf "%b" "\nExiting the program now...\n\n"
fi
sleep 5
fi
if [ "$typecheck00" = "2" ]; then
clear
printf "%b" "\nExiting the program now...\n\n"
sleep 5
fi
if [ "$typecheck00" != "1" ] && [ "$typecheck00" != "2" ]; then
typecheck00=2
clear
printf "%b" "\nExiting the program now...\n\n"
sleep 5
fi
done
