#!/bin/sh

#Main Menu
while [ "$typecheck00" != "3" ]; do
clear
printf "%b" "\n#### Coffee Linux Pacman Switcher Tool 1.0.7 ####\n"
printf "%b" "\n#### DO NOT RUN AS SUDO/ROOT ####\n"
printf "%b" "\nWhat type of pacman repo do you want? (Default: 1)\n"
printf "%b" "\n1 - Stable\n"
printf "%b" "\n2 - Testing\n"
printf "%b" "\n3 - Exit the program\n"

read -r typecheck00
case $typecheck00 in
 1) printf "%b" "\nStable selected. Switching now..\n" ;;
 2) printf "%b" "\nUnstable selected. Switching now..\n" ;;
 3) printf "%b" "\nExit selected.. Exiting now\n" ;;
 *) printf "%b" "\nUnrecognized option, selecting default..\n" ;;
esac

clear

if [ "$typecheck00" = "1" ]; then
sudo rm /etc/pacman.conf
sudo cp /opt/pacman-stable.conf /etc/pacman.conf
sudo pacman -Syy
clear
printf "%b" "\nSwitched to stable repos successfully...\n\n"
sleep 5
fi
if [ "$typecheck00" = "2" ]; then
sudo rm /etc/pacman.conf
sudo cp /opt/pacman-unstable.conf /etc/pacman.conf
sudo pacman -Syy
clear
printf "%b" "\nSwitched to unstable repos successfully...\n\n"
sleep 5
fi
if [ "$typecheck00" = "3" ]; then
clear
printf "%b" "\nExited program successfully...\n\n"
sleep 5
fi
if [ "$typecheck00" != "1" ] && [ "$typecheck00" != "2" ] && [ "$typecheck00" != "3" ]; then
typecheck00=1
sudo rm /etc/pacman.conf
sudo cp /opt/pacman-stable.conf /etc/pacman.conf
sudo pacman -Syy
clear
printf "%b" "\nSwitched repos successfully...\n\n"
sleep 5
fi
done
